In [2]:
import numpy as np

In [22]:
a = np.array([1,2,3])
print(a)
print(a.shape)
b= np.array([
    [1,2,3],
    [4,5,6]
])
print(b)
print(b.shape)

[1 2 3]
(3,)
[[1 2 3]
 [4 5 6]]
(2, 3)


In [15]:
c=np.arange(1,10,2)
print(c)
print(c.shape)
d= np.linspace(1,10,5)
print(d)

[1 3 5 7 9]
(5,)
[ 1.    3.25  5.5   7.75 10.  ]


In [19]:
print(c.reshape(2,3))

ValueError: cannot reshape array of size 5 into shape (2,3)

In [24]:
np.random.randint(1,1000,(3,3,5))

array([[[984, 213,  80, 533, 436],
        [833, 334, 970, 736,  31],
        [498, 743, 731, 522, 769]],

       [[770,  58,  63, 661, 970],
        [ 35, 465, 177, 803, 131],
        [ 63, 503, 554, 844, 923]],

       [[175, 878, 413, 907, 773],
        [500,  77, 135, 909, 542],
        [621, 979, 945, 445, 468]]])

In [25]:
x= np.array([
    [2,3,4],
    [5,6,7]
])
y= np.array([
    [1,2,3],
    [5,6,7]
])

In [26]:
print(x+y)
print(x-y)
print(x*y)
print(x/y)
print(x**y)
print(x%y)


[[ 3  5  7]
 [10 12 14]]
[[1 1 1]
 [0 0 0]]
[[ 2  6 12]
 [25 36 49]]
[[2.         1.5        1.33333333]
 [1.         1.         1.        ]]
[[     2      9     64]
 [  3125  46656 823543]]
[[0 1 1]
 [0 0 0]]


In [27]:
print(np.sin(x))
print(np.cos(x))
print(np.tan(x))
print(np.arcsin(x))


[[ 0.90929743  0.14112001 -0.7568025 ]
 [-0.95892427 -0.2794155   0.6569866 ]]
[[-0.41614684 -0.9899925  -0.65364362]
 [ 0.28366219  0.96017029  0.75390225]]
[[-2.18503986 -0.14254654  1.15782128]
 [-3.38051501 -0.29100619  0.87144798]]
[[nan nan nan]
 [nan nan nan]]


C:\Users\Dell\AppData\Local\Temp\ipykernel_14524\869906023.py:4: RuntimeWarning: invalid value encountered in arcsin
  print(np.arcsin(x))
